const ActionTypes = {
	USER_SIGN_UP: "USER_SIGN_UP",
	USER_SIGN_IN: "USER_SIGN_IN",

	CREATE_POST: "CREATE_POST",
	UPDATE_POST: "UPDATE_POST",
	DELETE_POST: "DELETE_POST",

	GET_ALL_POSTS: "GET_ALL_POSTS",
	GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
	GET_ALL_TAGS: "GET_ALL_TAGS",

	GET_POST: "GET_POST",
	GET_CATEGORY: "GET_CATEGORY",
	GET_TAG: "GET_TAG",

	CREATE_CATEGORY: "CREATE_CATEGORY",
	DELETE_CATEGORY: "DELETE_CATEGORY",

	CREATE_TAG: "CREATE_TAG",
	DELETE_TAG: "DELETE_TAG",
};

export default ActionTypes;
