const ActionTypes = {
	USER_SIGN_UP: "USER_SIGN_UP",
	USER_SIGN_IN: "USER_SIGN_IN",

	CREATE_POST: "CREATE_POST",
	UPDATE_POST: "UPDATE_POST",
	DELETE_POST: "DELETE_POST",
	GET_ALL_POSTS: "GET_ALL_POSTS",
	GET_POST: "GET_POST",
};

export default ActionTypes;
